[package]
name = "app"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
cpal = "0.16.0"
voice_input = { path = "../voice_input" }
wake_detection = { path = "../wake_detection" }